In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [45]:
a=np.arange(5,10,2)
print(a)
print(type(a))
print(a.ndim)

[5 7 9]
<class 'numpy.ndarray'>
1


In [79]:
arr=np.ones((4,2))
print(type(arr))
print(arr.size)
print(arr.shape)

<class 'numpy.ndarray'>
8
(4, 2)


In [24]:
arr1=np.ones((4,3))
print(arr1)
print(type(arr1))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


In [23]:
arr4 = np.arange(0, 10, 2)
print(arr4)
print(type(arr4))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [33]:
arr2 = np.zeros((3, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
print(a[2])

9


In [80]:
a=np.array(([1,2,3],[4,7,8],[9,3,1]))
print(a)
print(type(a))
print(a.ndim)
print(a.size)
print(a.shape)

[[1 2 3]
 [4 7 8]
 [9 3 1]]
<class 'numpy.ndarray'>
2
9
(3, 3)


In [81]:
print(a[1,1])

7


In [82]:
print(a)
r=a[:2,:2]
print(r)
r1=a[::-1,::-1]
print(r1)
r2=a[::-1,::-3]
print(r2)
print(a[:,0])
print(a[0,:])
print(a[(0,2)])

[[1 2 3]
 [4 7 8]
 [9 3 1]]
[[1 2]
 [4 7]]
[[1 3 9]
 [8 7 4]
 [3 2 1]]
[[1]
 [8]
 [3]]
[1 4 9]
[1 2 3]
3


In [93]:
print(a)
print(a[:,0])
print(a[0,:])
print(0,)

[[1 2 3]
 [4 7 8]
 [9 3 1]]
[1 4 9]
[1 2 3]


In [97]:
a=np.full((3,2),32)
print(a)

[[32 32]
 [32 32]
 [32 32]]


In [106]:
s=np.eye(5,dtype='int16')
print(s)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [109]:
c=np.arange(1,13)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [115]:
#reshaping
x=c.reshape(3,4)
print(x)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [133]:
y=c.reshape((3,2,2))
print(y)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [119]:
print(c.reshape(1,12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [120]:
print(c.reshape(12))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [132]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
ar=a.ravel()
print(ar)
b=a.flatten()
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [134]:
x=np.array([[10,20,30]])
print(x)
r=np.repeat(x,10,axis=0)
print(r)
s=np.repeat(x,10,axis=1)
print(s)

[[10 20 30]]
[[10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]]
[[10 10 10 10 10 10 10 10 10 10 20 20 20 20 20 20 20 20 20 20 30 30 30 30
  30 30 30 30 30 30]]


In [136]:
e=np.empty((3,3),dtype='int16')
print(e)

[[-19488 -19162    499]
 [     0      0      0]
 [     0      0      2]]


In [138]:
c=np.random.randint(-4,10,size=(3,4))
print(c)

[[-2 -1 -2  8]
 [ 1 -1  5  8]
 [ 0  0  8  3]]


In [140]:
c=np.random.rand(3,2)
print(c)

[[0.46919536 0.38112974]
 [0.61262778 0.16259771]
 [0.17852396 0.23142571]]
