In [2]:
import numpy as np

In [2]:
a=5
print(5)
b=6
print(b)
print(type(a),type(b))

5
6
<class 'int'> <class 'int'>


In [18]:
a=np.array((1,2,3))
print(a)
print(type(a))
b=np.array([1,2,3])
print(b)
print(b.dtype)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
int32


In [17]:
a=np.array([1,1.0,2.5,5.7])
print(a)
print(a.dtype)
#In this case, dtype=np.int32 is used to specify that the array should have a data type of 32-bit integers.


[1.  1.  2.5 5.7]
float64


NumPy follows a type hierarchy when determining the data type of an array. In this hierarchy, floating-point numbers have a higher precedence than integers. Therefore, when you mix integers and floating-point values in an array, the resulting data type will typically be a floating-point type to preserve the decimal places.

In [16]:
a=np.array(['a','g',4,4.5,3])
print(a)
print(a.dtype)#U for unicode

['a' 'g' '4' '4.5' '3']
<U32


In [95]:
a=np.arange(10,50,3)
print(a)
print(type(a))
print(a.ndim)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]
<class 'numpy.ndarray'>
1


In [97]:
#indexing
print(a[-2])
print(a[5])
#slicing
print(a[2:8:2])
print(a[12:4:-3])

46
25
[16 22 28]
[46 37 28]


In [38]:
print(sum(a))
print(len(a))
print(a.ndim)

413
14
1


In [4]:
#2D
ar=np.array([[1,2,3],[4,5,6],[7,8,9],[3,6,9]])
print(ar)
print(type(ar))
print(ar.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 6 9]]
<class 'numpy.ndarray'>
2


In [56]:
#indexing
print(ar[2][0])
print(ar[3,1])

7
6


In [51]:
print(ar)
r1=ar[:2,:2]
print(r1)
r2=ar[::-1,::-1]
print(r2)
r3=ar[::-1,:3]
print(r3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 6 9]]
[[1 2]
 [4 5]]
[[9 6 3]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[3 6 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]


In [54]:
print(ar[:,0])
print(ar[0,:])
print(ar[(0,1,2,3),(0,1,2,2)])#bind row X col

[1 4 7 3]
[1 2 3]
[1 5 9 9]


In [64]:
print(ar)
#print(len(ar))
print(ar.dtype)
print(ar.itemsize)
print(ar.size)
print(ar.nbytes)
print(ar.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 6 9]]
int32
4
12
48
(4, 3)


In [68]:
ar=np.array([1,2,3])
print(ar)
print(len(ar))
print(ar.dtype)
print(ar.itemsize)
print(ar.size)
print(ar.nbytes)
print(ar.shape)

[1 2 3]
3
int32
4
3
12
(3,)


In [88]:
#creating an array of zeros
a=np.zeros((2,3),dtype='int16')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

[[0 0 0]
 [0 0 0]]
int16
2
12


In [9]:
#creating an array of ones
a=np.ones((3,4))
print(a)
print(a.dtype)
print(a.itemsize)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
8


In [10]:
a=np.array(["a","b"])
print(a)
print(a.dtype)
print(a.itemsize)

['a' 'b']
<U1
4


In [11]:
#creating an array having all the elemets same
a=np.full((3,3),5)
print(a)
print(type(a))

[[5 5 5]
 [5 5 5]
 [5 5 5]]
<class 'numpy.ndarray'>


In [12]:
#creating a matrix of nan
b=np.full((3,2),np.nan)
print(b)

[[nan nan]
 [nan nan]
 [nan nan]]


In [13]:
a=np.diag([1,2,3,4])#creating a diagonal matrix
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [5]:
#changing type of elements in an array
a=np.eye(3,4,dtype='int16')#creating an identity matrix
b=np.eye(3)
c=b.astype(int)
print(a)
print(b)
print(c)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
a=np.arange(1,16)
print(a)
print(a.ndim)
print(a.nbytes)
print(a.dtype)
print(a.itemsize)
print(a.size)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
60
int32
4
15
(15,)


In [17]:
#reshaping an array
x=a.reshape((3,5))
print(x)
print(x.ndim)
print(x.nbytes)
y=a.reshape((3,5,1))
print(y)
print(y.ndim)
print(y.nbytes)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
60
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]
3
60


#Difference Between Flatten and Ravel Functions
Flatten always produces a one-dimensional copy, whereas ravel attempts to provide a one-dimensional view of the original matrix. Be cautious since altering the returned matrix from ravel may make changes to the original matrix.
Modifying the content of the array created by flatten has no effect on the original array.
Because no memory is duplicated, ravel is frequently quicker, but you must be extra cautious when altering the matrix it returns.
Because flatten is a function of an ndarray object, it can only be used with legitimate numpy arrays. In contrast, ravel() is a library-level function that may be called on any object that can be appropriately parsed.

In [18]:
# both creates 1 dimensional array from any multidim
a=y.ravel()# creates a view of original array
print(a)
a[1]=100
print(a)
print(y)
b=y.flatten() # creates a copy of original array
print(b)
b[0]=111
print(b)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[  1 100   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[[  1]
  [100]
  [  3]
  [  4]
  [  5]]

 [[  6]
  [  7]
  [  8]
  [  9]
  [ 10]]

 [[ 11]
  [ 12]
  [ 13]
  [ 14]
  [ 15]]]
[  1 100   3   4   5   6   7   8   9  10  11  12  13  14  15]
[111 100   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[[  1]
  [100]
  [  3]
  [  4]
  [  5]]

 [[  6]
  [  7]
  [  8]
  [  9]
  [ 10]]

 [[ 11]
  [ 12]
  [ 13]
  [ 14]
  [ 15]]]


In [18]:
print(y.ravel())
print(y)
print(y.flatten())#Therefore, modifications made to the flattened array will not affect the original array. 
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


In [22]:
# repeat: it repeats the element of an existing array to form new arrays
r=np.repeat(y,2,axis=0)
print(r)#in axis 0 whole matrix repeat 2 times
#but in axis 1 every element of matrix repeat
r1=np.repeat(y,2,axis=2)
print(r1)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]
[[[ 1  1]
  [ 2  2]
  [ 3  3]
  [ 4  4]
  [ 5  5]]

 [[ 6  6]
  [ 7  7]
  [ 8  8]
  [ 9  9]
  [10 10]]

 [[11 11]
  [12 12]
  [13 13]
  [14 14]
  [15 15]]]


In [20]:
#creating empty matrix
e=np.empty((3,3))
print(e)
e=np.empty((3,3),dtype='int16')
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-13200  18035    469]
 [     0      0      0]
 [     0      0      2]]


In [8]:
#random
##random.rand() is used to create a matrics of random numbers between 0 and 1.
d=np.random.rand(4,5)
print(d)
print(type(d))
b=np.random.randint(-5,15,size=(3,3))
print(b)
c=np.random.randint(-5,15,size=(3))
print(c)

[[0.06535648 0.89687002 0.80923398 0.34680191 0.26817246]
 [0.73713131 0.84596181 0.90929987 0.9620632  0.08762314]
 [0.67939729 0.19832809 0.53345296 0.43251821 0.90170799]
 [0.30822614 0.40273097 0.57053556 0.62024748 0.65949129]]
<class 'numpy.ndarray'>
[[-3 -3  5]
 [11  0  5]
 [ 0  3 -1]]
[-5 -5  8]


In [9]:
#view method: it will generate an array same as existing one
# if we change data in view then change will reflect in the original one as well.
a=np.array([10,20,30])
print(a)
b=a.view()
b[1]=50
print(b)
print(a)

[10 20 30]
[10 50 30]
[10 50 30]


In [10]:
x=np.arange(10,23)
print(x)
c=x.copy()
print(c)
c[2]=55
print(c)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22]
[10 11 12 13 14 15 16 17 18 19 20 21 22]
[10 11 55 13 14 15 16 17 18 19 20 21 22]
[10 11 12 13 14 15 16 17 18 19 20 21 22]


In [23]:
a=np.arange(1,7)
print(a+1)
print(a%2)
print(a/1)
print(a**2)

[2 3 4 5 6 7]
[1 0 1 0 1 0]
[1. 2. 3. 4. 5. 6.]
[ 1  4  9 16 25 36]


In [25]:
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print(b+1)
print(b%2)
print(b/1)
print(b**2)

[[2 3 4]
 [5 6 7]]
[[1 0 1]
 [0 1 0]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1  4  9]
 [16 25 36]]


In [27]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])

In [28]:
A=np.array([[2,0,3],[4,1,8],[7,5,9]])
print(A)
B=np.array([[10,20,30],[50,40,70],[90,60,80]])
print(B)

[[2 0 3]
 [4 1 8]
 [7 5 9]]
[[10 20 30]
 [50 40 70]
 [90 60 80]]


In [29]:
A.transpose()

array([[2, 4, 7],
       [0, 1, 5],
       [3, 8, 9]])

In [38]:
print(B.T)
print(np.trace(B))
print(A+B)
#for multiplication of two matrices
print(A.dot(B))
print(np.matmul(A,B))
print(A@B)

[[10 50 90]
 [20 40 60]
 [30 70 80]]
130
[[12 20 33]
 [54 41 78]
 [97 65 89]]
[[ 290  220  300]
 [ 810  600  830]
 [1130  880 1280]]
[[ 290  220  300]
 [ 810  600  830]
 [1130  880 1280]]
[[ 290  220  300]
 [ 810  600  830]
 [1130  880 1280]]


In [40]:
#Determent of matrics
print(np.linalg.det(A))
#inverse
print(np.linalg.inv(A))


-22.99999999999999
[[ 1.34782609 -0.65217391  0.13043478]
 [-0.86956522  0.13043478  0.17391304]
 [-0.56521739  0.43478261 -0.08695652]]


In [33]:
x=np.arange(12).reshape(3,4)
print(x)
print(x.sum())
print(x.sum(axis=0))#for colwise
print(x.sum(axis=1))#for rowwise
print(x.cumsum())#cumulative sum
print(x.cumsum(axis=0))
print(x.std())#standard daviation
print(x.std(axis=1))
print(x.mean(axis=0))#mean

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
3.452052529534663
[1.11803399 1.11803399 1.11803399]
[4. 5. 6. 7.]


In [34]:
# it creates boolean array
b=x>5
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
print(x[b])

[ 6  7  8  9 10 11]


In [36]:
x[b]=89
print(x)

[[ 0  1  2  3]
 [ 4  5 89 89]
 [89 89 89 89]]


In [38]:
print(np.where(x<4))
#provides index for which the condition is true
#it returns tuple corresponding to the index

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [41]:
y=np.arange(2,8)
print(y)
z=np.where(y<4,y,12)#values are replaced by 25 for which condition is false
print(z)

[2 3 4 5 6 7]
[ 2  3 12 12 12 12]


In [54]:
for i in x:
    for j in i:
        print(j,end=' ')
    print()

0 1 2 3 
4 5 6 7 
8 9 10 11 


In [55]:
for item in np.nditer(x):
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11


In [58]:
for item in np.nditer(x,order='F'):#for col wise
    print(item)

0
4
8
1
5
9
2
6
10
3
7
11


In [59]:
for item in np.nditer(x,order='C'):#for row wise
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11


In [62]:
y=np.arange(12,24).reshape(3,4)
y

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
for i,j in np.nditer([x,y]):
    print(i,j)

0 12
1 13
2 14
3 15
4 16
5 17
6 18
7 19
8 20
9 21
10 22
11 23


In [68]:
np.split(x,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [72]:
np.split(x,[1,2])

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [42]:
for i in x.flat:
    print(i)

0
1
2
3
4
5
89
89
89
89
89
89


In [ ]:
#reading and writing from/in files
